# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'ppa:cran/poppler'
          packages:
            - libwebp-dev
            - libpoppler-cpp-dev
            - poppler-data
            - libtesseract-dev
            - libleptonica-dev
            - tesseract-ocr-eng
            
addons:
  apt:
    packages:
      - libwebp-dev
      - libpoppler-cpp-dev
      - poppler-data
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng